### ISSUE TITLE
Reinstate wcomponents "optional tests" i.e. selenium tests

### ISSUE THREAD

**Issue by ricksbrown** [BorderTech/wcomponents#10]
Unit tests only used to run manually on developer machines and therefore selenium tests could expect to find the right browsers installed etc.

Now with tests being run as part of Travis CI the selenium tests are going to need to be smarter.

For now they are disabled.

May be able to solve using Opensauce: https://saucelabs.com/opensauce/

**Comment by jonathanaustin** [comment]
The Selenium tests are a good way to test the contract between the client and the server.

Ideally, we need a selenium test for each component. Rather than reinstating the existing selenium tests, which were never specifically put together to test individual components, it would be better to create a new set of tests.

The logical spot for these new tests would be in the wcomponents_bundle module. This module brings the theme and server side together.

These new tests could then be setup to run in sauce labs and could also be used on custom themes.

**Comment by ricksbrown** [comment]
Sounds like a plan.
I suggest two stages:

1. Initial setup (basically get one single selenium test running in `wcomponents-bundle`)
2. Write tests for each component.

It does not have to be the same person doing step 1 and step 2.
Maybe @JohnMcGuinness would be interested in step 2?

**Comment by marksreeves** [comment]
Fixed by #754
