### ISSUE TITLE
some requirejs modules are being fetched even though they are in the layer file

### ISSUE THREAD

**Issue by ricksbrown** [BorderTech/wcomponents#1068]
the `common` layer file seems not to be honored for some dynamically generated "if i have one of these then load this" modules.

**Comment by ricksbrown** [comment]
Started tracking this down. It does not look like a single cause but rather lines of code like [this](https://github.com/BorderTech/wcomponents/blob/5e08f4e94373866d1727eb3d1e22a66290f65649/wcomponents-theme/src/main/js/wc/dom/impliedARIA.js#L9).

Modules in the `ui` namespace should not be pulled in so early and should not really be dependencies of the `dom` namespace. `ui` modules should be leaves on the dependency tree, and only required as dependencies by other `ui` modules.

**Comment by marksreeves** [comment]
Fixed in PR #1084: we had some poorly thought-out internal dependencies. The files which were being fetched despite being in the layer were all down-stream dependencies of those modules which were required outside of the layer inclusion mechanism. This was definitely our flaw and not an upstream issue.
