### ISSUE TITLE
AJAX actions can be skipped by manually manipulating posted data

### ISSUE THREAD

**Issue by Joshua-Barclay** [BorderTech/wcomponents#113]
Many projects (for example, **[redacted]**) will have implemented necessary business functions in AJAX commands attached to `onChange` events of input fields (e.g. a dropdown).

It is possible for users to maliciously (using dev tools/proxy) or accidentally (latest Safari version not honoring selected values) change the value of a component without triggering the `onChange` event.

It is not reasonable to trust application teams to implement secondary verification of posted values on a per-case basis within their Java code.

WComponents should automatically handle this scenario by either rejecting the `POST` with updated values or ignoring the updated values.

**Comment by Joshua-Barclay** [comment]
A possible solution would be to update au.gov.immi.sfp.ui.web.AbstractInput.handleRequest(Request) to first check whether the input was an AJAX trigger and if so check if the value has been updated.
The update could then be ignored or an exception could be thrown.

**Comment by marksreeves** [comment]
I am not entirely sure what you are getting at. Are you concerned about asynch requests being made where the trigger value has not changed or subsequent POSTs which include ajax trigger components where the value of that trigger has changed but a subsequent asynch request was not made?

Asynch requests are not necessarily kicked off by `change` events (but we can assume they are for simplicity). As you rightly point out it is pretty trivial to change a value in a https POST which completely by-passes any possible in-browser checking or to make an update in browser which avoids the `change` event cycle: but as the asynch request is initiated by the `change` event then by-passing the `change` event will not give you a request to handle. This is why I am confused.

Is this it?

1. If you get a request; **and**
2. the request contains one or more ajax trigger components (assume one for the rest of this list); **and** 
3. the ajax trigger component's value has changed; **but**
4. the asynch request action which _should_ have been triggered by that change has not yet been triggered; **then** 
5. ignore the change?

That sounds a little dangerous to me since the whole point of asynchronous requests is they are asynchronous and it may simply have not arrived yet whereas you could run the `actionOnChange` off the changed POSTed value.

**Comment by marksreeves** [comment]
Oh, and sorry Joshua but I redacted a couple of bits of your issue.

**Comment by Joshua-Barclay** [comment]
Yes, your step by step breakdown explains the issue and the solution I have suggested.

I agree with your suggestion - a better option is to run the *actionOnChange* event when the value change is detected in *com.github.bordertech.wcomponents.AbstractInput.handleRequest(Request)*.
This will be ensure it is handled much more gracefully for non-malicious users (e.g. the Safari bug).

**Comment by marksreeves** [comment]
Thanks for the clarification. `com.github.bordertech.wcomponents.AbstractInput.handleRequest` will trigger the `actionOnChange` if one is present (through `com.github.bordertech.wcomponents.AbstractInput.doHandleChanged`) so my suggestion is a no-op. This doesn't really help with your issue though. 

I think we are trying to get to a point where `com.github.bordertech.wcomponents.AbstractInput` (or any framework component) can determine if a 'changed' value is changed by fair means rather than foul and revert (or ignore) any which are deemed 'foul'. Interesting issue: may need more than one coffee.

**Comment by marksreeves** [comment]
I have given this more thought and I think the 'train tunnel' scenario makes it impossible to enforce ajax action validation at an abstract (framework) level. Let me explain:

1. A user is on a train and the train enters a tunnel and loses connectivity;
2. whilst disconnected the user selects a WCheckBox which has an `actionOnChange` and is an trigger for a WAjaxControl;
3. the system attempts to make an asynchronous call but it fails as there is no connectivity;
4. the user keeps working (perhaps oblivious depending how the target components are configured) and just after connectivity is revived clicks a submit button;
5. the POST includes the WCheckBox which is now selected so `handleRequest` will invoke the Action attached to its `actionOnChange` - the POST has the WCheckBox in a selected state but the Action which should have been handled by an asynchronous call has never been invoked;
6. is this a malicious or erroneous attempt to bypass AJAX invoked Actions? Neither!

It may be valid to put some safeguards into a particular application so that workflow and business rules can be enforced but I cannot see how we can force the order of Action in the framework. I am, however, very happy to listen to all opinions to the contrary and suggestions as to how we go about this.

@Joshua-Barclay I am going to leave this issue open for a while but I do not think it is able to be addressed. If you have any workarounds for the train tunnel scenario which are applicable globally **please** let us know.

**Comment by Joshua-Barclay** [comment]
@marksreeves I agree with you that the framework must handle this gracefully and should not attempt to disrupt the user because such an event has occurred.

When processing the POST in this scenario, the framework should try to mimic the AJAX function as best it can (e.g. executing the actionOnChange) and then validate based on the resulting screen state. This is a very close approximation of how the AJAX functionality should have behaved had it worked correctly (malicious or accidental).

The only inconsistency I can see with this approach is if applications rely on logic in preparePaintComponent() running after the AJAX call to correctly setup the screen state.

```
WRadioButtonSelect parentCategory = new WRadioButtonSelect({"A", "B", "C"});
WRadioButtonSelect childType = new WRadioButtonSelect({"1", "2", "3"});
WTextField text = new Text();
...
parentCategory.setAction(new Action()
{
    public void execute()
    {
        childType.setSelected("1");
    }
});
...
protected void preparePaintComponent()
{
    if("1".equals(childType.getSelected())
    {
        text.setMandatory(true);
    }
}
```
In the above example, the AJAX not running on the client side will result in the text field not being set to mandatory.

Ideally the framework should handle this scenario, but that would requite inconsistent execution of 'pre-render' code during POST handling.

**Comment by marksreeves** [comment]
@jonathanaustin is there any chance of looking into the request processing lifecycle to ensure `actionOnChange` Actions are called as early as possible? I am looking at the various interceptors and I think @Joshua-Barclay may have a particularly muddy chain of priority because of some particularly complicated interplays between ajax and subordinates.

Some of this complication _does_ come from the ancient determination to not treat a web app as a web app but pretend it is a Swing app with a malicious driver. So, for example, we cannot call `doHandleChanged` until we have run the subordinate interceptors because of the need to test disabled and hidden but the subordinate rules may depend on a missing (ajax) invocation of an Action. Perhaps it is time to assume if a component is not disabled in a post it is not disabled?

As for the scenario in @Joshua-Barclay's last code snippet (which is a prime candidate for use of WSubordinateControl but that is beside the point): we should look at getting some documentation and examples around the life cycle and when and how to set properties on components. This type of scenario can rationally only be a doco issue, not than an API issue. The inherited document [Technical overview](https://github.com/BorderTech/wcomponents/wiki/Technical-overview#breakdown-of-the-action-and-render-phases) may need to be revisited. Is it still accurate? Is it useful? Does it need more detail and to be written in a more digestible manner? I am happy to take on the copy writing if one or more Java dudes can provide me with draft content.

**Comment by ricksbrown** [comment]
The only reason the server side implementation of subordinate exists, in my opinion, is to ensure the ui is rendered in the correct state (i.e. on building response). Running subordinate rules on handling request is something we should consider ditching entirely.

**Comment by marksreeves** [comment]
Not running subordinate rules in Java during the request cycle is a different kettle of fish but one worth looking into. In the meantime could we continue to queue AJAX requests if offline and then send them on reconnect? @ricksbrown

Even in the case of there being no subordinate interceptors we still have an issue of asynchrocity which prevents us being able to solve this issue (without recourse to a global mind-reading mechanism). 

If a particular use-case insists on using asynchronous updates **and requires** linear/synchronous updates then it is only that use-case which can determine how to handle the obvious incompatibility of the two. 

If I remember correctly this issue originally stemmed from @Joshua-Barclay finding a new and exciting Safari "feature" which we have subsequently worked around. The extension of the bug caused by Safari to a general principle is one which cannot be handled in an abstract manner any further than we already attempt to. I am sorry but the fact that asynchronous actions cannot be guaranteed to occur in a specific order is not a flaw: it is their nature.
