### ISSUE TITLE
MenuBar overflows from a tab's content if the 'wc-neg-margin' class is present

### ISSUE THREAD

**Issue by JohnMcGuinness** [BorderTech/wcomponents#1132]
See this image for the problem. 

![image](https://cloud.githubusercontent.com/assets/14829333/24124260/fe10ea26-0e16-11e7-99d0-9c9902a3bd70.png)

The fix is to change the size of the margin for ```wc-neg-margin``` from ```-1em``` to ```-0.5em```.

![image](https://cloud.githubusercontent.com/assets/14829333/24124310/397d5c34-0e17-11e7-9c1d-e410195ca348.png)

@marksreeves

**Comment by marksreeves** [comment]
Whilst the described use-case is valid it is unusual. We cannot allow for all possible combinations or nesting of components, therefore we will not be enabling this use-case. It would be better implemented using [application custom CSS](https://github.com/BorderTech/wcomponents/wiki/Adding-custom-CSS). The remainder of this comment details the reasons for this decision.

The class `wc-neg-margin` was created to solve one particular use-case: to "dock" a WMenu of Type.BAR to the header of a WSection (or WPanel of types CHROME or ACTION) when the menu CSS could not automatically cause the docking behaviour as the menu was any of:

* in a Layout (rather than a non-layout content container); or
* preceded by a non-rendering HTML element (such as a script or off-screen element) and is therefore not the first child of the content container; or
* a combination of these such as being in the `nth` cell of a vertical FlowLayout where each of the preceding cells contain non-rendered, moved, or out-of-viewport components.

These conditions are, admittedly, arcane so we provide a description of the use of this class in the [wiki entry on WMenu](https://github.com/BorderTech/wcomponents/wiki/WMenu#forcing-the-docking-style). This specifies that this class should only be used to dock the WMenu to the header of a WSection or certain types of WPanel. We do not expose the class in HTMLClassProperties for exactly this reason: it is not a general use class.

The space around the content of a headed section is tied to size of the negative margin applied through the class `wc-neg-margin` by a Sass variable whereas the space around the content of a tabpanel is not tied to the space around the content of a section.
