### ISSUE TITLE
Include file selectors when serializing a form for AJAX

### ISSUE THREAD

**Issue by ricksbrown** [BorderTech/wcomponents#129]
Traditionally when serializing a form for an AJAX POST file selectors would be ignored - it was not possible to AJAX them.

Now it is possible to natively AJAX them we should probably look at including them when we do AJAX.

**Comment by marksreeves** [comment]
Rick, can I just clarify: this would only apply to single uploads (WFileWidget) when **not** AJAX-enabled since this is the only situation in which an [input in the file-upload state](https://html.spec.whatwg.org/multipage/forms.html#file-upload-state-(type=file)) would have a value when triggering an AJAX request.

Given this is an edge case (why not AJAX enable the file widget to immediately upload?) and would be most common in applications which are specifically designed to be compatible with older browsers (remember our IE6 customer) I am not convinced of the need.

If an application wants AJAX uploading of files then it can already be done through the file widget. If they want a limit of a single file they can set `maxFiles` to 1. I, therefore, counter-propose that we make **all file uploads immediate/ajax** since we already have the FauxJax polyfill for <del>rubbish</del><ins>special</ins> browsers and then this issue becomes moot.

**Comment by marksreeves** [comment]
WFileWidget is deprecated. No further action.
