### ISSUE TITLE
Combobox - Selection of option from the suggestion list is not keyboard operable

### ISSUE THREAD

**Issue by Likhasinh** [BorderTech/wcomponents#1442]
When a WDropdown has DropdownType.COMBO and the suggestion list is opened, an option cannot be selected using a keyboard (i.e using the <Enter> key as per the WAI-ARIA Authoring Practices 1.1). This is confirmed in Firefox, Safari and Chrome and is assumed that this does not work in IE too.

**Expect**
When the option in the list has focus (using arrow up/down key), pressing the <Enter> key selects the option and the selected option is displayed the text box part of the combo and the list collapses (closes).

**Actual**
Arrow up/down the list displays the option in the the text box part of the combo, pressing the <Enter> key does not select the option and the list stays expanded (opened).

**Comment by marksreeves** [comment]
This is due to a race between listboxAnalog's keyDown handler and comboBox's keyDown handler where preventDefault in one breaks the other. 

listboxAnalog does need to handle the `RETURN` key but does not need to handle `SPACE` as the WAI-ARIA authoring practices have changed. This means we can remove the prevention of the default action which was to prevent the page scroll on `SPACE`.

Within combo's key handler we probably don't care if preventDefault has been called. A combo is a leaf component - can't have nested content - so should always handle key events within itself.

**Comment by marksreeves** [comment]
OK, so this is much more deeply problematic than I first thought and is linked to the promise-ication of Observer. This becomes apparent when looking at the now broken interaction of the `ESCAPE` key behaviour of a combo inside a dialog. 

What is happening is a simple race but the priority of notification of an Observer instance is now wrapped up in a promises.all and each Promise is, of course, asynchronous and independent. This results in the simple early-normal-late event priorities not necessarily being honoured. So, in the case of combo inside a dialog even making dialog's listener a lower priority results in it being called before the keydown event listener in a combo as the listener for a dialog is attached to the dialog and for some reason the listener for a combo was attached to the body. 

The upshot of this is that all key event listeners have to be attached to the component rather than attaching some to the body and some to individual components. This has the advantage of enabling lazy wire-up of key event listeners and a slight performance improvement from removing body listeners. 

This is no longer a good first issue: it is a big ol' mess of an issue so I am taking it on myself.
