### ISSUE TITLE
File with no MIME type fails validation

### ISSUE THREAD

**Issue by kandula-aswin** [BorderTech/wcomponents#1584]
For file [upload widgets](https://github.com/BorderTech/wcomponents/wiki/WMultiFileWidget), if application [sets file type(s)](https://github.com/BorderTech/wcomponents/wiki/WMultiFileWidget#limit-file-types), it is validated on the server.

At server an opensource Apache tool is used to [detect](https://tika.apache.org/1.1/detection.html) the MIME type. Where files that do not have [known MIME type](https://www.iana.org/assignments/media-types/media-types.xhtml), tika performs a magic detection and returns a default MIME type.

For example HPE Records Manager electronic file reference is saved with extension `tr5`. Browsers do not recognise it's MIME type as it does not have it, where as Apache Tika detects and returns MIME type of `application/x-tika-msoffice`. Due to mismatch the validation fails.

**Comment by marksreeves** [comment]
I can confirm this is an issue. When a MIME type is not available the `tika` tool returns a made-up string rather than null or an empty String. Whilst `tika` is configurable with an alternate MIME map it may be more convenient to determine that part of the return value which identifies one of these 'not-real' types and make the tested type `null`.

From a validation perspective it is better to have the default validator accept a file with no determinable type than to reject a file with no determinable type. 

Obviously it would be better still if we allow consuming applications to provide a MIME type map or, at the very least, a mechanism to determine when to ignore MIME tests. Do we want to go down the path of if no MIME type check file extensions? That is only reliable for windows and even then is fraught with potential error.

We should also provide examples and documentation around how to extend the default validation for type.
