### ISSUE TITLE
WAudio WVideo schemas and Java API allows hidden but not SubordinateTarget

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#1718]
WAudio and WVideo may be hidden in Java and have hidden in their schemas but do not implement SubordinateControl to allow them to be unhidden in client.

Interestingly both implement Disableable even though this is incompatible with HTML spec.

@jonathanaustin Should we break out Hideable as a new Interface to make SubordinateTarget more granular as we did this Disableable?

This may be over-engineering but SubordinateTarget should just allow a control to be targetted, not necessarily allow any particular kind of action (as the JavaScript implementation of subordinate actions allow for complex extensions to do data setting etc).

**Comment by jonathanaustin** [comment]
We could look at breaking out a new interface `Hideable`, but the problem is `isHidden` is defined on the `WComponents` interface and `setHidden` is on `AbstractWComponent`.

To do it correctly would involve doing a breaking API change and removing these methods from `WComponent` and `AbstractWComponent`.

However, as an interim we could still create a marker interface `Hideable` (with no methods) and put it in on the appropriate Components and do the breaking API change later. The `Hide` and `Show` actions could still be changed to check for the new interface, similar to how `Disable` and `Enable` check for `Disableable`.

As far as the `SubordinateTarget` interface, it does already allow a control to be targeted without any particular action. It is only in the specific Subordinate Actions that check if the component has the capability (eg `Disableable`) and applies the action.
