### ISSUE TITLE
Fix WSubMenu to include its ID in the request when clicked

### ISSUE THREAD

**Issue by jonathanaustin** [BorderTech/wcomponents#252]
WSubMenu should include its ID as a request parameter when it is clicked.

**Comment by marksreeves** [comment]
We have decided to not address this issue because it is inconsistent with all other components which fetch content on open (eg WTab, WCollapsible). The original report was due to a piece of schema doc which stated the submenu id would be passed as the "submitting button" in some conditions and this comment was the cause of the potential inconsistency.

WSubMenu actions may be run when the WSubMenu opens if it has an AJAX mode (lazy, eager, dynamic) as the WSubMenu id is then the ajax trigger id.
