### ISSUE TITLE
Unify various Alignment enums into a single enum

### ISSUE THREAD

**Issue by JohnMcGuinness** [BorderTech/wcomponents#299]
Currently there are numerous enums called `Alignment`. These are `ColumnLayout.Alignment`, `FlowLayout.Alignment`, `ListLayout.Alignment`, `WColumn.Alignment` and `WTableColumn.Alignment`.

All of these have the values `Alignment.LEFT`, `Alignment.CENTER` and `Alignment.RIGHT`. `FlowLayout.Alignment` also has the value `Alignment.VERTICAL`.

I would like to propose unifying all of these enums into a single enum `com.github.bordertech.wcomponents.layout.Alignment` with the values `LEFT`, `CENTER` and `RIGHT`. Also, to replace the `VERTICAL` value in `FlowLayout.Alignment`, I propose to add the `com.github.bordertech.wcomponents.layout.Orientation` enum with values of `HORIZONTAL` and `VERTICAL`.

A `FlowLayout` would by default have orientation of `Orientation.HORIZONTAL`, if the flow should be vertical then the developer could set the orientation:

```
myFlowLayout.setOrientation(Orientation.VERTICAL);
```

The vertically oriented `FlowLayout` could then still be aligned with an `Alignment` value.

WDYT @ricksbrown, @jonathanaustin, @marksreeves

**Comment by marksreeves** [comment]
I think we should keep FlowLayout out of this. It has an alignment enum but it is not the same kind of thing as the other alignments (not just in the inclusion of `VERTICAL`). Column alignments are cosmetic and simply provide a general left-center-right alignment of the content in a given column (ColumnLayout, WColumn and WTableColumn). 

The Alignment enum in FlowLayout is structural and indicates the relationship of the layout's contained components to each other as well as their spatial arrangement on screen. It is a subtle but real difference which makes FlowLayout.Alignment fail the _is a_ test relative to the column alignments.

IMO this member should not be `Alignment` at all but that comes down to the tricky business of naming API constructs in an unambiguous and not-too-silly way (FlowLayout.Layout could be considered silly). Something like FlowLayout.Direction does not really indicate the nature of `CENTER` or `RIGHT` when it comes to a FlowLayout as they are still (default) left to right; FlowLayout.Arrangement is a bit florid (see what I did there?) but could be a bit more meaningful.

Maybe @jonathanaustin has something more sensible to add?

**Comment by jonathanaustin** [comment]
Consolidating the Alignment enum is a good idea. It is an opportunity to adjust/clean up the Layouts. But as it a significant change, it will need to be nutted out.

We also need to make sure the change is backward compatible and deprecate the old API code.

So I am going to dump some ideas and see what you think…..

Since writing the Layout showcases, I have been thinking of raising the idea of deprecating **WFlowLayout** and replacing it with **VerticalLayout** and **HorizontalLayout**.

This would make it easier for projects to determine which layout to use and hopefully simplifies the API for each Layout.

**HorizontalLayout** would still support the “flow” of cells ie LEFT, CENTRE, RIGHT. But this is not necessary for **VerticalLayout**.

We could then look at a new **CellAlignment** enum that all Layouts (including GridLayout) use.

The **CellAlignment** could cover all 9 positions:-

TOP_LEFT,
TOP_CENTRE,
TOP_RIGHT,
MIDDLE_LEFT,
MIDDLE_CENTRE,
MIDDLE_RIGHT,
BOTTOM_LEFT,
BOTTOM_CENTRE,
BOTTOM_RIGHT

We could also look at setting a “default” alignment on the Layouts so it does not need to be set for each cell. But ColumnLayout could still allow for each Column to override the default.

@marksreeves @ricksbrown @JohnMcGuinness What do you think?

**Comment by JohnMcGuinness** [comment]
@jonathanaustin this is interesting and raises many questions for me. 

Firstly, a minor addition to **CellAlignment** would be to add LEFT_BASELINE, CENTER_BASELINE and RIGHT_BASELINE. And maybe if it were called **Pos**, there may be other usecases where it might be useful outside of specifying a position in a layout's cell, and **Pos** is a bit more general and usable in other scenarios.

The only way I could think of making it backwards compatible would be to overload the methods and constructors that use the existing and new **Alignment** values. Then deprecate the old values. Or as @marksreeves mentioned in the PR #315 I could create a tool do the migration. It would simply change imports for the existing **Alignment** enums to import the new enum.

I would be interested to hear your reasons for deprecating **FlowLayout**. If a **HorizontalLayout** were added would it be a layout component like **WRow** or a layout for **WPanel**. I would favour having a new component. Perhaps a **HorizontalLayout** component and **WRow** could be merged.

Laying out components in WComponents can be confusing to start with as there are *Layouts* and *Layout Components*, I couldn't explain why some are components and others are properties of **WPanel**. **WPanel** also has the additional function of providing different presentation.

As a learning exercise for myself, with initially no intention of pushing this to my fork, I started to create a component that I called **HBox**. It's a single row, horizontal layout component. It is similar to **WRow**, but does not require the user to *box* the component in a **WColumn**. It also does not require a percentage for each component, but one can be supplied. And each component can optionally have a **GrowPriority** applied to it. **GrowPriority** has values of **ALWAYS** or **NEVER**. If supplied, the percentage is the starting size before additional space is allocated according to **GrowPriority**. It is rendered in html as *flex-flow: row nowrap*. I pushed it to my fork earlier if you'd like a look.

Personally, I favour keeping **FlowLayout**, perhaps making it a stand alone component, and adding the concept of **Orientation** or **ContentBias** to it. Any way thats my morning brain dump. :smiley:

**Comment by JohnMcGuinness** [comment]
Perhaps if a new FlowLayout component is created it could be called a **FlowPane**. Just sayin.

**Comment by jonathanaustin** [comment]
Like `FlowLayout`, `HorizontalLayout` and `VerticalLayout` are not new components but are layouts used on `WPanel`.

The `HBox` component you mentioned would simply become a `WPanel` with a `HorizontalLayout`.

Another reason to deprecate `FlowLayout` is its API can be confusing. Its current API allows a `vertical gap` and a `horizontal gap` to be set, but these can be meaningless depending on which "type" of flow you are using. With `HorizontalLayout` and `VerticalLayout` you only need one gap value and it is obvious what it applies to.

As far as an upgrade tool, I think it is always better if projects can pick up a new baseline without having to run a migration tool. So just as you suggested, we would need to overrload some methods or even create some new method names. This is why I was leaning towards calling the new enum `CellAlignment` as it is differentiated from the old enum and can have its own setter/getters.

**Comment by JohnMcGuinness** [comment]
@jonathanaustin No the`HBox` is a component used for layout, like `WRow`, but with different layout semantics. It doesn't really matter anyway. I was doing it as an exercise for myself.

My understanding of `vgap` in a horizontal `FlowLayout` is that when the child components need to wrap, the `vgap` is the gap between the rows in the layout, is that not right? In a `HorizontalLayout` when the components wrap into a new row would it be possible to specify the gap between the rows?

**Comment by marksreeves** [comment]
@JohnMcGuinness `vgap` is ignored in horizontal flows and `hgap` is ignored in vertical flows. I do not foresee this changing anytime soon.

I see very little worth in vertical flows. They can be constructed economically with `WPanel` is required and many components [as listed here](https://github.com/BorderTech/wcomponents/wiki/WComponent-content-models#flow-content-which-is-not-phrasing-content) will naturally flow vertically. Quite a few of these implement Marginable as well.

Reducing the layout components _will_ make building responsive apps easier funnily enough as we will have to make fewer rendering decisions in abstract components. Eventually we should be able to do away with almost all (if not all) of the purely layout components.

So my vote is to kill `FlowLayout.VERTICAL` and abort `VerticalLayout` or whatever it is you want to call it.

**Comment by marksreeves** [comment]
If left to myself (I am a browser guy remember, not a Java guy) I wouldn't have Layout components but I **do** see the **need** for them; so we can safely **ignore** my previous comment about killing `FlowLayout.VERTICAL` (I like to throw cats amongst pigeons but sometimes the pigeons fly away and sometimes the cat is a stuffed toy).

I am not _yet_ convinced that adding yet more Layout components is the way to improve the API. @jonathanaustin and I have done quite a lot of work to make in-app layout styling easier so we may be better off improving examples and doco on how to build custom layouts and leave the Java Layout components for simple screen structures and legacy support: they do make simple layouts for known implementations (e.g. corporate/enterprise [(in)|(ex)]tranet applications) quick and easy for experienced Java devs. Internet applications _may_ be better built with custom templates, [custom CSS](https://github.com/BorderTech/wcomponents/wiki/Adding-custom-CSS) and JS (see #172).

The point of all this is:

1. that @JohnMcGuinness original proposal to unify the Alignments for `WColumn`, `ColumnLayout` and `WTableColumn` should be implemented;
2. `FlowLayout` should not be included _at all_ in this unification;
3. we remove all discussion of other Layout API changes/fixes/improvements to [gitter](https://gitter.im/BorderTech/wcomponents) for a thorough discussion since **this issue** is **only** concerned with the Alignment enums.
