### ISSUE TITLE
WShuffler does not always honour the POSTed order

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#323]
In the wcomponents-examples-lde the is an example (hidden away in Other examples) `AjaxReplaceControllerExample`. In this example there is a WShuffler which is an AJAX controller.

When this control is used to re-order the options The subsequent AJAX POST contains the options in the order in which they are listed in the selection list. In the following sample we are interested in the values for eg-_0a2bb0b.

> wc_t=d3b68e65-f000-469c-bee3-68d24982b548&wc_s=5&_1a1a1=&_1c0a-h=x&eg-_0a2bb1b-h=x&eg-_0a2bb2b=1&eg-_0a2bb2b-h=x&eg-_0a2bb3b-h=x&eg-_0a2bb4b=1&eg-_0a2bb5b-h=x&eg-_0a2bb6b-h=x&eg-_0a2bb7b=1&eg-_0a2bb8b=&eg-_0a2bb9b=&eg-_0a2bb0b=0&eg-_0a2bb0b=1&eg-_0a2bb0b=4&eg-_0a2bb0b=3&eg-_0a2bb0b=5&eg-_0a2bb0b=2&eg-_0a2bb0b=6&eg-_0a2bb3b=3&eg-_0a2bb3b=2&_1c1a=0&wc_ajax=eg-_0a2bb0b

They were sent in the following order:

1. eg-_0a2bb0b:0 (Sunday)
2. eg-_0a2bb0b:1 (Monday)
3. eg-_0a2bb0b:4 (Thursday)
4. eg-_0a2bb0b:3 (Wednesday)
5. eg-_0a2bb0b:5 (Friday)
6. eg-_0a2bb0b:2 (Tuesday)
7. eg-_0a2bb0b:6 (Saturday)

The  guts of the control's action on change is simply to set the content of a WTextField:
``` java
// Given WTextField textField and WShuffler controller:
textField.setText(controller.getValueAsString());
```

The order in which the options were then returned to the UI in that WTextField were: 
> [Thursday, Monday, Friday, Tuesday, Saturday, Wednesday, Sunday]

There does not appear to be any correlation between the "order" of the options in the shuffler POST and the order in the WTextField's text.

I have fixed a bug in WMultiSelectPair's javascript which prevented it from being an Ajax controller for "shuffle" actions. This control _does_ appear to honour the shuffled order with an action ostensibly identical to that shown above.

**Comment by jonathanaustin** [comment]
This is happening because `WShuffler` uses the index of its `Options` as the identifier (ie the "value").

When `WShuffler` is used as an `AjaxTrigger`, the server state is changed to reflect the order of the client side but because the `WShufller` is not refreshed on the client it is still holding the index values of the old order. If the `WShuffler` continues to be used without a page refresh, then it is going to continue to be out of sync with the server side state.

As the index of the option is not reliable, `WShuffler` needs to be changed to use the `String` value of the `Option`, which is the same value used as its description. This will allow the server and client side to remain in sync.
