### ISSUE TITLE
Do not do server side XSLT Processing when theme.content.path is set

### ISSUE THREAD

**Issue by jonathanaustin** [BorderTech/wcomponents#377]
WComponents defaults to `server side` transforms. This can be enabled/disabled via:-

```
bordertech.wcomponents.xslt.enabled=false/true
```

For `server side` transforms, WComponents assumes the theme resources are in the classpath.

However, projects may not always have the theme resources in the classpath and want to load them from a static resource (eg from a different web server or resources defined in their war file). To load resources from a static resource, projects set a content path:-
```
bordertech.wcomponents.theme.content.path=theme/myTheme
```

So....if a project sets the theme content path then `server side` transforms become meaningless. This means `server side` transforms should only be honored when no content path has been set.

**Comment by marksreeves** [comment]
This bit me today whilst doing some testing with the examples jar built in the last release and a custom theme, so I heartily endorse this proposal.

Moreover, doing the XSLT processing in Java within WComponents should be a last resort. For enterprise applications an external processor would seem to be more appropriate and in many cases it is still more effective to distribute the XSLT processing to the end users (for intranet applications especially).

I suggest we change the default so that processing in WComponents is _off_ by default and is an opt-in, in addition to not doing XSLT processing in WComponents if a theme content path is set.

**Comment by jonathanaustin** [comment]
Have changed the default for server side transform to be disabled and included the logic that if a theme content path has been set then dont honor the server side transform.
