### ISSUE TITLE
WEmailField - Validation

### ISSUE THREAD

**Issue by AndrewTheJavaGuy** [BorderTech/wcomponents#516]
Looking at the WEmailField, it's currently using a regular expression to check for a valid email.

It may be an idea to look at moving this to the Apache Commons Email / Domain Validator modules instead (from commons-validator). This will give a comparable regular expression and have the added bonus of also being able to to TLD (Top Level Domain) validation off a IANA list (provided you enable it in Domain Validator as well)

Just a suggestion.

Thanks
Andrew

**Comment by marksreeves** [comment]
The email validator has to be code-compatible with whatever is used in JavaScript for in-client validation. I am unaware of the ability to export the commons-validator rules to JS but if you can point me to an instance where this has happened I would be happy to delve further.

**Comment by AndrewTheJavaGuy** [comment]
Here's a Javascript implementation of this: https://github.com/wix/commons-validator-js

A cursory analysis of the code looks like it's supporting the same methods of validation structure, but I did not fully check the domain.js to see if all the domain names match from the commons-domain library (which is the more useful part of the implementation).

**Comment by marksreeves** [comment]
I rather like the implementation but it is not suitable for production use. The use of a fixed (and cacheable) list of TLDs is problematic as it **will** result in false negatives if a new tld is released without the list being updated. The only way to use a tld check would be to be able to use a web service or similar to check a live list of current domains.

It is **not acceptable** to reject a potentially valid email address just because _we_ do not know about a tld. So for this reason I do not believe we should implement a library fix of this type.

@ricksbrown, @jonathanaustin Any remark about this?

**Comment by ricksbrown** [comment]
I know we all prefer the use of industry standard utilities where possible and therefore this issue is certainly worth considering and well worth raising, thanks @AndrewTheJavaGuy.

Our current implementation was deliberately designed to perform only the most basic checks since true email validation is impractical enough that we can consider it impossible. Everyone must decide how strict they will attempt to be. 

In our case @marksreeves is right, our premise is that rejecting a valid email address is unacceptable - we'd rather accept an invalid one. If implementing these libraries increases the chances of breaking this rule then I'd vote not to implement it.

**Comment by marksreeves** [comment]
I have been giving this more thought. Maybe it could be available as an opt-in? It should already be possible to add this type of validator within a consuming application. @jonathanaustin is there a **sensible** mechanism to add a custom validator from an external package? If so, maybe we should add a sample showing how. If not then perhaps we can leverage this enhancement request to make adding custom validators a bit easier?

On the client side a JavaScript implementation can be added using WApplication's `addJs...`methods or using a WTemplate so it can be supported as an opt-in per application or added to a custom implementation in the libs.

**Comment by marksreeves** [comment]
The email validation rules should be based on [the HTML spec](https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address) so does not provide room for extra "likely to be real" checking. 

I draw attention to the note (found at the above link):

> This requirement is a willful violation of RFC 5322, which defines a syntax for e-mail addresses that is simultaneously too strict (before the "@" character), too vague (after the "@" character), and too lax (allowing comments, whitespace characters, and quoted strings in manners unfamiliar to most users) to be of practical use here.
