### ISSUE TITLE
Add scss-lint to wcomponents-theme build?

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#55]
Another step to improve (and maintain) code quality. [scss-lint](https://github.com/brigade/scss-lint) is a Sass equivalent of eslint.  Scss-Lint is available as a [Maven plugin](https://github.com/brigade/scss-lint#maven-integration).

Do we add scss linting to the theme build? _Or_ perhaps generate a CI report if CSS style issues are not considered build-killer worthy?

I have added a config file (.scss-lint.yml) to the wcomponents-theme dir which can be used to apply our rules to scss either manually or in a compatible IDE (Atom does  this nicely). A glance at this config will show I have a few rules which I still think will eventually be reverted to defaults (more stringent).

**Comment by ricksbrown** [comment]
@marksreeves I believe for sure it should be part of the build because I find people (even myself) will neglect to run a separate "quality check" phase reliably. 

The question as to whether stylistic errors should ever actually fail the build is probably worth discussing, not just for scss-lint but for eslint and java checkstyle too. 

Maybe we should turn them all down to warning... Or maybe default to warn and only fail the build on the rare stylistic issues we consider critical.

**Comment by marksreeves** [comment]
@ricksbrown one more spanner for the works: scss-lint appears to be the "best" linter currently available in that is can easily manage all of the Sass (including variable interpolation) I have thrown at it whereas the npm compatible linters I have found do not (at all or with issues).

It does, however, mean that if we run this as part of the theme build with fail on error we will have to **move** the Sass compilation phase from npm to Maven. This is fine is we are going to remain Maven dependant but less so if we want to go to another build mechanism.

Still looking at other options for node.

**Comment by marksreeves** [comment]
Not an option until a useable linter is available upstream.
