### ISSUE TITLE
PhantomJS - Implement workaround for unsupported display: flex

### ISSUE THREAD

**Issue by Joshua-Barclay** [BorderTech/wcomponents#561]
Despite comments to the contrary PhantomJS 2.1.1 (latest) does not support `display: flex`.

The most significant aspect of this issue is that it prevents dialogs from displaying due to the following CSS selectors:

`dialog[open]{display: flex;} // ignored by PhantomJS`
`dialog{display: none;} // processed by PhantomJS`

In order to treat automated testing as a first-class user of WComponents it is in our interests to work around this issue until it is fixed in PhantomJS.

@marksreeves @ricksbrown

**Comment by marksreeves** [comment]
I would be very reticent to change the display model of dialogs. I have tried numerous options and flex provides optimum display under the varierty of conditions and interactions to which dialogs are exposed. Just setting the size of a dialog is controversial it not using flex. Whilst I change the display for real browsers used by actual people I am **absolutely** opposed to changing it because phantomJS is crap.

A sub-optimal (but quick and dirty) option is to have a dynamically loaded CSS for phantomJS as we do for IE8. This could change the display mode of anything which is flex to something else. I will not guarantee render or usability of positioning or resizing though.

**Comment by Joshua-Barclay** [comment]
Hi Mark,

You're right that we shouldn't change the behavior for all browsers. Rick and I thought that we could add styling such as the following:
`dialog[open]{display: block; display: flex;}`
Which should only change the behavior when flex is unsupported.

Although the lack of `flex` support affects all elements, I suspect it only really matters for dialogs.

Do you have a better suggestion for how we could work around this issue without affecting mainstream browsers?

**Comment by marksreeves** [comment]
If the `display: block;` line is added to the top of the flex mixin in `src/main/sass/_mixins-flex.scss` it will be applied to everything which uses flex layout; and if it is commented adequately I won't delete it during a brain-spasm 😖

Why do I _always_ come up with the most complex solution first?
