### ISSUE TITLE
WTable should implement AjaxTrigger

### ISSUE THREAD

**Issue by JohnMcGuinness** [BorderTech/wcomponents#581]
Selecting a row should be able to fire an AJAX request.

**Comment by ricksbrown** [comment]
Sounds like a sensible idea... It will take a bit of thought. Maybe should be a subordinate trigger too (if it isn't already, I forget).

**Comment by marksreeves** [comment]
It is not currently a subordinate trigger. The main difficulty is going to be around ring-fencing the Java API: since rows are not addressable directly one would have to make the table be the trigger in which case why not allow pagination or row expansion also trigger? This may it seem sensible or likely but I have fought off one request to make pagination an Ajax trigger in the recent past.

**Comment by marksreeves** [comment]
I have had a look at this and we are going to have some issues on the client. An expandable row controls its "sub" rows and therefore already has `aria-controls`. We also use `aria-controls` to indicate the relationship between an ajax trigger and its target components (though this _may_ be overkill). If the row expansion is dynamic or lazy we also have the row as an ajax trigger already: but a trigger to GET its content.

The `row` role in a `grid`/`treegrid` is the only control which allows both expansion and selection. I would be extraordinarily happy to see the back of row expansion (it is a bad, bad metaphor reminiscent of Lotus Notes views) but I don't see it going away any time soon (more's the pity).

We _could_ consider allowing WTable to be an ajax trigger if it does not have row expansion, but that seems a bit half baked.

Another option is to take row selection off of the row and back into a separate selection component (as it used to be many, many years ago). This would allow us to take the selection mechanism and its associated ajax (if it was implemented) off of the row but at the cost of reducing usability: we used to try to capture off-control clicks but I don't think that is really necessary.

Ultimately though a table is **NOT** a selection tool so should we really be enabling rather primitive UI design practices?

**Comment by marksreeves** [comment]
Note for @jonathanaustin : if we do this we will run into the same issues as we have with WTree. We will not know if an ajax request is to open a branch or to trigger the WAjaxControl. The solution we have with WTree is not ideal but it does work and uses the same pattern as WMultiFileWidget.

A corollary to this is that we will almost certainly have to improve sub-row loading in that opening an AJAX loaded set of children should just load those children and not the whole table.

This note is just here for reference when we get around to doing this. I would like to see the row loading optimisation in v2 - especially since it is part of the UI/data separation we need.
